- path: /etc/profile.d/bash-functions.sh
  permissions: '0755'
  content: |
    # Functions
    function nse() { docker exec -it "$1" bash ; }
    function fluf() { if [ -z "$1" ] ; then fleetctl list-unit-files ; else fleetctl list-unit-files | grep "$1" ; fi }
    function flm() { if [ -z "$1" ] ; then fleetctl list-machines ; else fleetctl list-machines | grep "$1" ; fi }
    function flu() { if [ -z "$1" ] ; then fleetctl list-units ; else fleetctl list-units | grep "$1" ; fi }
    function wfluf() { watch -n1 "if [ -z \"$1\" ] ; then fleetctl list-unit-files ; else fleetctl list-unit-files | grep \"$1\" ; fi" ; }
    function wflm() { watch -n1 "if [ -z \"$1\" ] ; then fleetctl list-machines ; else fleetctl list-machines | grep \"$1\" ; fi" ; }
    function wflu() { watch -n1 "if [ -z \"$1\" ] ; then fleetctl list-units ; else fleetctl list-units | grep \"$1\" ; fi" ; }
    function elr() { if [ -z "$1" ] ; then etcdctl ls --recursive ; else etcdctl ls --recursive | grep "$1" ; fi }
    function shortcuts() {
      echo "nse    :: Exec into a docker container"
      echo "fluf   :: List fleet unit files, if an argument is passed, the result will be greped"
      echo "flm    :: List fleet machines, if an argument is passed, the result will be greped"
      echo "flu    :: List fleet units, if an argument is passed, the result will be greped"
      echo "nse    :: Exec into a docker container"
      echo "wfluf  :: Watch List fleet unit files, if an argument is passed, the result will be greped"
      echo "wflm   :: Watch List fleet machines, if an argument is passed, the result will be greped"
      echo "wflu   :: Watch List fleet units, if an argument is passed, the result will be greped"
      echo "elr    :: List all etcd entries, if an argument is passed, the result will be greped"
      echo "jc     :: journalctl
      echo "fl     :: fleetctl"
      echo "ed     :: etcdctl"
      echo "syc    :: systemctl"
      echo "lk     :: locksmithctl"
      echo "shortcuts      :: This help command"
    }
    #-
    # Aliases
    alias jc='journalctl'
    alias fl='fleetctl'
    alias ed='etcdctl'
    alias syc='systemctl'
    alias lk='locksmithctl'

    echo 'use the `shortcuts` command to get a list of shortcuts.'
