- path: /etc/profile.d/bash-functions.sh
  permissions: '0755'
  content: |
    # Functions
    function nse() { docker exec -it "$1" bash ; }
    function fluf() { if [ -z "$1" ] ; then fleetctl list-unit-files ; else fleetctl list-unit-files | grep "$1" ; fi }
    function flm() { if [ -z "$1" ] ; then fleetctl list-machines ; else fleetctl list-machines | grep "$1" ; fi }
    function flu() { if [ -z "$1" ] ; then fleetctl list-units ; else fleetctl list-units | grep "$1" ; fi }
    function wflm() { watch -n1 "if [ -z \"$1\" ] ; then fleetctl list-machines ; else fleetctl list-machines | grep \"$1\" ; fi" ; }
    function wflu() { watch -n1 "if [ -z \"$1\" ] ; then fleetctl list-units ; else fleetctl list-units | grep \"$1\" ; fi" ; }
    function elr() { if [ -z "$1" ] ; then etcdctl ls --recursive ; else etcdctl ls --recursive | grep "$1" ; fi }
    #-
    # Aliases
    alias jc='journalctl'
    alias fl='fleetctl'
    alias ed='etcdctl'
    alias syc='sudo systemctl'
