# Github keys command
- path: /opt/bin/fleet-key
  permissions: 0755
  owner: root:root
  content: |
    #!/bin/bash
    for key in `etcdctl ls -p --recursive authorized_keys | grep -E "[^\/]$"` ; do etcdctl get $key | xargs echo -n  ; done

- path: /etc/ssh/sshd_config
  permissions: '0600'
  owner: root:root
  content: |
    # Use most defaults for sshd configuration.
    AuthorizedKeysFile .ssh/authorized_keys
    AuthorizedKeysCommand /opt/bin/fleet-key
    AuthorizedKeysCommandUser root
    PasswordAuthentication no
    UsePrivilegeSeparation sandbox
    ClientAliveInterval 180
    UseDNS no
