-
  name: calico-node.service
  command: start
  content: |
    [Unit]
    Description=Calico per-host agent
    Requires=network-online.target
    After=network-online.target

    [Service]
    Slice=machine.slice
    EnvironmentFile=/etc/environment
    Environment=CALICO_DISABLE_FILE_LOGGING=true
    Environment=HOSTNAME=${COREOS_PRIVATE_IPV4}
    Environment=IP=${COREOS_PRIVATE_IPV4}
    Environment=FELIX_FELIXHOSTNAME=${COREOS_PRIVATE_IPV4}
    Environment=CALICO_NETWORKING=false
    Environment=NO_DEFAULT_POOLS=true
    Environment=ETCD_ENDPOINTS=127.0.0.1:2379
    ExecStart=/usr/bin/rkt run --inherit-env --stage1-from-dir=stage1-fly.aci \
      --volume=modules,kind=host,source=/lib/modules,readOnly=false \
      --mount=volume=modules,target=/lib/modules \
      --trust-keys-from-https quay.io/calico/node:v0.19.0

    KillMode=mixed
    Restart=always
    TimeoutStartSec=0

    [Install]
    WantedBy=multi-user.target
