-
  name: calico-node.service
  command: start
  content: |
    [Unit]
    Description=Calico per-host agent
    Requires=network-online.target
    After=network-online.target

    [Service]
    Slice=machine.slice
    Environment=CALICO_DISABLE_FILE_LOGGING=true
    Environment=HOSTNAME=var!private_ipv4
    Environment=IP=var!private_ipv4
    Environment=FELIX_FELIXHOSTNAME=var!private_ipv4
    Environment=CALICO_NETWORKING=false
    Environment=NO_DEFAULT_POOLS=true
    Environment=ETCD_ENDPOINTS=http://var!private_ipv4:2379
    ExecStart=/usr/bin/rkt run --inherit-env --stage1-from-dir=stage1-fly.aci \
      --volume=modules,kind=host,source=/lib/modules,readOnly=false \
      --mount=volume=modules,target=/lib/modules \
      --trust-keys-from-https quay.io/calico/node:v0.19.0

    KillMode=mixed
    Restart=always
    TimeoutStartSec=0
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
