- path: /etc/profile.d/fleet-ssh-config.sh
  permissions: '0755'
  content: |
    rm -f $HOME/.ssh/fleet_rsa
    /usr/bin/ssh-keygen -f $HOME/.ssh/fleet_rsa -P "" > /dev/null
    cat $HOME/.ssh/fleet_rsa.pub | etcdctl set /authorized_keys/$USER/rsa.pub > /dev/null
    eval `ssh-agent -s`
    ssh-add $HOME/.ssh/fleet_rsa &> /dev/null
